name: Docker Push
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v3 
        - name: download image artifact
          uses: actions/download-artifact@v4
          with:
            name: my-ml-pipeline-image
        - name: Load docker image
          run: docker load -i my-ml-pipeline-image.tar
        - name: login to dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: push docker image
          run: docker push ${{ secrets.DOCKER_USERNAME }}/my-ml-pipeline:latest

